spring:
  redis:
    host: 10.211.55.4
    port: 6379
    database: 0
    timeout: 1800000
    password: "123456"
    lettuce:
      pool:
        max-wait: -1
        max-idle: 5
        min-idle: 0
        max-active: 20